"""empty message

Revision ID: 794ee6b32465
Revises: de2393709c3a
Create Date: 2023-08-12 03:54:04.702607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794ee6b32465'
down_revision = 'de2393709c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_details', schema=None) as batch_op:
        batch_op.alter_column('homeworld',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_details', schema=None) as batch_op:
        batch_op.alter_column('homeworld',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
